# Generated by Django 5.2.15 on 2026-06-14 07:08

import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=payments.models._generate_transaction_id, editable=False, max_length=36, unique=True)),
                ('kind', models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_tr_user_id_d7ba42_idx'), models.Index(fields=['status'], name='payments_tr_status_96e6c0_idx'), models.Index(fields=['kind'], name='payments_tr_kind_e61d61_idx')],
            },
        ),
    ]
